# spring.application.name=jt-blogs

# server.port=1205

# spring.datasource.url=jdbc:mysql://localhost/blog
# spring.datasource.username=root
# spring.datasource.password=root

spring:
  application:
    name: jt-blogs

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost/blog?createDatabaseIfNotExist=true
    username: root
    password: root

server:
  port: 1200
